config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'games#show'
  # Blackjack
  get 'blackjack', to: 'blackjack#index'
  post '/start_game', to: 'blackjack#start_game'
  post '/new_card', to: 'blackjack#new_card'
  get '/bank_new_card', to: 'blackjack#bank_new_card'
  post '/bank_new_card', to: 'blackjack#bank_new_card'
  # Longest Word
  get 'longest_word', to: 'longest_word#index'
  post '/new', to: 'longest_word#new'
  post "/score", to: "longest_word#score"
  # Wagon Race
  get 'wagon_race', to: 'wagon_race#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blackjack_controller.rb
class BlackjackController < ApplicationController
  attr_accessor :player_cards, :bank_cards, :player_score, :bank_score, :result
  before_action :initialize_game_state

  CARDS = {
    "2_of_hearts" => 2, "2_of_diamonds" => 2, "2_of_clubs" => 2, "2_of_spades" => 2,
    "3_of_hearts" => 3, "3_of_diamonds" => 3, "3_of_clubs" => 3, "3_of_spades" => 3,
    "4_of_hearts" => 4, "4_of_diamonds" => 4, "4_of_clubs" => 4, "4_of_spades" => 4,
    "5_of_hearts" => 5, "5_of_diamonds" => 5, "5_of_clubs" => 5, "5_of_spades" => 5,
    "6_of_hearts" => 6, "6_of_diamonds" => 6, "6_of_clubs" => 6, "6_of_spades" => 6,
    "7_of_hearts" => 7, "7_of_diamonds" => 7, "7_of_clubs" => 7, "7_of_spades" => 7,
    "8_of_hearts" => 8, "8_of_diamonds" => 8, "8_of_clubs" => 8, "8_of_spades" => 8,
    "9_of_hearts" => 9, "9_of_diamonds" => 9, "9_of_clubs" => 9, "9_of_spades" => 9,
    "10_of_hearts" => 10, "10_of_diamonds" => 10, "10_of_clubs" => 10, "10_of_spades" => 10,
    "jack_of_hearts" => 10, "jack_of_diamonds" => 10, "jack_of_clubs" => 10, "jack_of_spades" => 10,
    "queen_of_hearts" => 10, "queen_of_diamonds" => 10, "queen_of_clubs" => 10, "queen_of_spades" => 10,
    "king_of_hearts" => 10, "king_of_diamonds" => 10, "king_of_clubs" => 10, "king_of_spades" => 10,
    "ace_of_hearts" => 11, "ace_of_diamonds" => 11, "ace_of_clubs" => 11, "ace_of_spades" => 11
  }

  def index
  end

  def start_game
    @deck = CARDS.keys.shuffle
    @player_cards = [@deck.pop, @deck.pop]
    @bank_cards = [@deck.pop, @deck.pop]
    @player_score = @player_cards.map { |card| CARDS[card] }.sum
    @bank_score = @bank_cards.map { |card| CARDS[card] }.sum
    @result = nil
    save_to_session
    render :index
  end

  def new_card
    if session[:deck].nil? || session[:deck].empty?
      start_game  # Si pas de partie en cours, on en démarre une nouvelle
    else
      initialize_game_state
      @player_cards.push(@deck.pop)
      @player_score = @player_cards.map { |card| CARDS[card] }.sum
      end_game if @player_score > 21
      save_to_session
      render :index
    end
  end

  def bank_new_card
    until @bank_score > 21 || @bank_score > @player_score
      @bank_cards.push(@deck.pop)
      @bank_score = @bank_cards.map { |card| CARDS[card] }.sum
    end
    end_game
    save_to_session
    render :index
  end

  def end_game
    if @player_score > 21
      @result = "Vous avez perdu"
    elsif @bank_score > 21
      @result = "Vous avez gagné"
    elsif @player_score > @bank_score
      @result = "Vous avez gagné"
    elsif @player_score < @bank_score
      @result = "Vous avez perdu"
    else
      @result = "Égalité"
    end
  end

  private

  def initialize_game_state
    @player_cards = session[:player_cards] || []
    @bank_cards = session[:bank_cards] || []
    @player_score = session[:player_score] || 0
    @bank_score = session[:bank_score] || 0
    @result = session[:result] || nil
    @deck = session[:deck] || []
  end

  def save_to_session
    session[:player_cards] = @player_cards
    session[:bank_cards] = @bank_cards
    session[:player_score] = @player_score
    session[:bank_score] = @bank_score
    session[:result] = @result
    session[:deck] = @deck
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
  end
end

app/controllers/longest_word_controller.rb
require 'open-uri'
require 'json'

class LongestWordController < ApplicationController
  attr_accessor :letters
  before_action :initialize_game_state

  VOWELS = %w(A E I O U Y)

  def new
    @letters = Array.new(5) { VOWELS.sample }
    @letters += Array.new(5) { (('A'..'Z').to_a - VOWELS).sample }
    @letters.shuffle!
    save_to_session
    render :index
  end

  def score
    @letters = params[:letters].split
    @word = (params[:word] || "").upcase
    @included = included?(@word, @letters)
    @english_word = english_word?(@word)

    render :index
  end

  private

  def initialize_game_state
    @letters = session[:letters] || []
  end

  def save_to_session
    session[:letters] = @letters
  end

  def included?(word, letters)
    word.chars.all? { |letter| word.count(letter) <= letters.count(letter) }
  end

  def english_word?(word)
    response = URI.open("https://dictionary.lewagon.com/#{word}")
    json = JSON.parse(response.read)
    json['found']
  rescue
    false
  end
end

app/controllers/wagon_race_controller.rb
class WagonRaceController < ApplicationController
  def index
  end
end

app/views/blackjack/index.html.erb
<section class="w-100 h-100 d-flex flex-column justify-content-between align-items-center">
  <h1 class="m-0">Black Jack Game</h1>

  <div class="game-status d-flex flex-row gap-3 w-100 px-2">
    <div class="player-status mx-auto border border-2 px-2">
      <p class="m-0">Vos cartes :</p>
      <div class="cards-container d-flex gap-2">
        <% @player_cards&.each do |card| %>
          <%= image_tag "cards/#{card}.png", class: "card-img", alt: card %>
        <% end %>
      </div>
      <p class="m-0">Votre score : <%= @player_score %></p>
    </div>
    <div class="player-status mx-auto border border-2 px-2">
      <p class="m-0">Cartes du banquier:</p>
      <div class="cards-container d-flex gap-2">
        <% @bank_cards&.each do |card| %>
          <%= image_tag "cards/#{card}.png", class: "card-img", alt: card %>
        <% end %>
      </div>
      <p class="m-0">Score du banquier: <%= @bank_score %></p>
    </div>
  </div>

<% if @result == nil %>
  <div class="game-options d-flex flex-row gap-3">
    <%= form_with(url: new_card_path, method: :post, local: true) do |f| %>
      <%= f.submit "New card", class: "button button-secondary retro blue" %>
    <% end %>
    <%= form_with(url: bank_new_card_path, method: :post, local: true) do |f| %>
      <%= f.submit "Stand", class: "button button-secondary retro blue" %>
    <% end %>
  </div>
<% else %>
    <p><%= @result.upcase %></p>
<% end %>
  <div class="game-options d-flex flex-row gap-3">
    <%= form_with(url: start_game_path, method: :post, local: true) do |f| %>
      <%= f.submit "Start again", class: "button button-secondary retro green" %>
    <% end %>

    <%= link_to "Back to games", root_path, class: "button button-secondary retro red" %>
  </div>
</section>

app/views/games/show.html.erb
<section>
  <h1 class="text-center blink mb-0">Retro games</h1>
  <div class="h-100 d-flex flex-column justify-content-center align-items-center gap-4">
    <p class="text-center typewriter ">Select a game to play :</p>
    <%= link_to "Blackjack", blackjack_path, class: "button button-primary retro red w-50" %>
    <%= link_to "Longest Word", longest_word_path, class: "button button-primary retro green w-50" %>
    <%= link_to "Wagon Race", wagon_race_path, class: "button button-primary retro blue w-50" %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Retro games</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=VT323" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <main class="container">
      <%= yield %>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/longest_word/index.html.erb
<section class="w-100 h-100 d-flex flex-column justify-content-between align-items-center">
  <h1>Longest Word Game</h1>

<div class="w-100">
  <div id="grid" class="d-flex flex-row justify-content-center mx-auto px-4 w-75 flex-wrap gap-3">
    <% @letters.each do |letter| %>
      <div class="letter border border-2"><%= letter.capitalize %></div>
    <% end%>
  </div>

  <div id="game-form">
    <form action="/score" method="POST">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag :letters, @letters %>
      <div class="input-group w-50 mx-auto mt-4">
        <input type="text" name="word" class="form-control rounded-0">
        <input type="submit" value="Play" class="button button-secondary retro blue rounded-0">
      </div>
    </form>
  </div>
</div>
  <% if @word %>
    <div class="mt-4 uppercase">
      <h3>RESULT :</h3>
      <% if @included %>
        <% if @english_word %>
          <p><strong>Congratulations!</strong> <%= @word %> is a valid English word!</p>
        <% else %>
          <p>Sorry but <strong><%= @word %></strong> does not seem to be a valid English word...</p>
        <% end %>
      <% else %>
        <p>Sorry but <strong><%= @word %></strong> can't be built out of this letters</p>
      <% end %>
    </div>
  <% end %>
  <div class="d-flex flex-row gap-3">
    <%= form_with(url: new_path, method: :post, local: true) do |f| %>
      <%= f.submit "Start again", class: "button button-secondary retro green" %>
    <% end %>
    <%= link_to "Back to games", root_path, class: "button button-secondary retro red" %>
  </div>
</section>

app/views/wagon_race/index.html.erb
<section class="w-100 h-100 d-flex flex-column justify-content-between align-items-center">

  <h1 class="text-center m-0">Wagon Race</h1>
  <hr>
  <div class="mb-3">
  <p class="m-0">player 1 press Q</p>
  <p class="m-0">player 2 press P</p>
  </div>
  <!-- You race HTML code here -->
  <table class="racer-table mx-4">
    <tr id="player1-race">
      <td class="active"></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td class="final"></td>
    </tr>
    <tr id="player2-race">
      <td class="active"></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td class="final"></td>
    </tr>
  </table>
  <hr>
  <p class="winner"></p>
  <div class="button">
    <button class="button button-secondary retro green">Start again</button>
    <%= link_to "Back to games", root_path, class: "button button-secondary retro red" %>
  </div>
  <%= javascript_include_tag "wagon_race" %>
</section>